config/routes.rb
Rails.application.routes.draw do


  resources :planets do
  	root to: 'planets#index'

  end
end

app/models/planet.rb
class Planet < ActiveRecord::Base

	mount_uploader :picture, PictureUploader
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

	def index
		@planets = Planet.all
	end

	def new
		@planet = Planet.new
	end

	def create 
		@planet = Planet.new(planet_params)
		if @planet.save
			redirect_to planets_path
		else
			redirect_to new_planet_path
		end
	end

	def edit
		@planet = Planet.where(id: params[:id]).first
	end

	def update
		@planet = Planet.where(id: params[:id]).first
		@planet.update_attributes(planet_params)
		if @planet.save
			redirect_to planets_path
		else
			redirect_to new_planet_path
		end
	end

	def show 
		@planet = Planet.where(id: params[:id]).first
	end

	def destroy
		@planet = Planet.find(params[:id]).destroy
	end

private 

	def planet_params
		params.require(:planet).permit(:id, :name, :info, :picture)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class = "center_main_text", id ="wt">Солнечная система</h1>

<%= yield %>

</body>
</html>

app/views/planets/edit.html.erb
<%= form_for(@planet, html: { multipart: true }) do |f| %>
<h2 align = "center">Редактирование Планеты</h2>

<div align = "center">

	<p><%= f.label :id %></br>
	<%= f.text_field :id %></p>

	<p><%= f.label :name %></br>
	<%= f.text_field :name %></p>

	<p><%= f.label :info %></br>
	<%= f.text_area :info %></p>

<span class="picture">
    <%= f.file_field :picture %></p>
</span>

	<%= f.submit %>

<% end %>

</div>

app/views/planets/index.html.erb
<div class="osvetlenie">
	<table width = "40%", align = "center", id ="wt">
		<tr>
			<th><%= link_to image_tag("sun.png", alt: "Солнце"),       planet_path(Planet.all.find_by_id(9)) %>Солнце</th>
			<th><%= link_to image_tag("mercury.png", alt: "Меркурий"), planet_path(Planet.all.find_by_id(1)) %>Меркурий</th>
			<th><%= link_to image_tag("venera.png", alt: "Венера"),    planet_path(Planet.all.find_by_id(2)) %>Венера</th>
			<th><%= link_to image_tag("earth.png", alt: "Земля"),      planet_path(Planet.all.find_by_id(3)) %>Земля</th>
			<th><%= link_to image_tag("mars.png", alt: "Марс"),        planet_path(Planet.all.find_by_id(4)) %>Марс</th>
			<th><%= link_to image_tag("jupiter.png", alt: "Юпитер"),   planet_path(Planet.all.find_by_id(5)) %>Юпитер</th>
			<th><%= link_to image_tag("saturn.png", alt: "Сатурн"),    planet_path(Planet.all.find_by_id(6)) %>Сатурн</th>
			<th><%= link_to image_tag("uran.png", alt: "Уран"),        planet_path(Planet.all.find_by_id(7)) %>Уран</th>
			<th><%= link_to image_tag("neptun.png", alt: "Нептун"),    planet_path(Planet.all.find_by_id(8)) %>Нептун</th>
		</tr>
	</table>
</div>

<%= render 'shared/ss' %>

app/views/planets/new.html.erb
<%= form_for(@planet, html: { multipart: true }) do |f| %>
<h2 align = "center">Создание новой планеты</h2>

<div align = "center">

	<p><%= f.label :id %></br>
	<%= f.text_field :id %></p>

	<p><%= f.label :name %></br>
	<%= f.text_field :name %></p>

	<p><%= f.label :info %></br>
	<%= f.text_area :info %></p>

<span class="picture">
    <%= f.file_field :picture %></p>
</span>

	<%= f.submit %>

<% end %>

</div>

app/views/planets/show.html.erb
<div class = "center_main_text", id="wt">
	<%= image_tag @planet.picture.url if @planet.picture? %>
	<h3><%= @planet.name %></h3>

<% if @planet.id == 1 %> 

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>3,3<sup>.</sup>10<sup>23</sup>кг. (0,055 массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>4870 км. (0,38 диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>5,43 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>максимум 430 <sup>o</sup>C, минимум -180 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>58,65 земных суток</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>0,387 а.е., то есть 58 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>88 земных суток</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>47,9 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>3,7 м/c<sup>2</sup></th></tr>
	</table>
</div>

	<% else %>

<% if @planet.id == 2 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>4,87<sup>.</sup>10<sup>24</sup>кг. (0,815 массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>12100 км. (0,949 диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>5,25 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>максимум +480 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>243 земных суток</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>0,723 а.е., то есть 108 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>224,7 земных суток</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>35 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>8,9 м/c<sup>2</sup></th></tr>
	</table>
</div>

	<% else %>

<% if @planet.id == 3 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>5,976<sup>.</sup>10<sup>24</sup>кг.</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>12756 км.</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>5,518 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>максимум +58 <sup>o</sup>C, минимальная -90 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>23 часа 56 минут 4,1 секунды</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>1 а.е., то есть 150 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>365,24219 суток</th></tr>
		<tr align = "left" ><th>Площадь поверхности:</th><th>510,2 млн.км<sup>2</sup></th></tr>
		<tr align = "left" ><th>Объем:</th><th>1,083<sup>.</sup>1012 км<sup>3</sup></th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>29,8 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>9,8 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 4 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>6,4<sup>.</sup>10<sup>23</sup>кг. (0,107 массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>6670 км. (0,53 диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>3,95 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>-23 <sup>o</sup>C на большей части поверхности,</br> -150 <sup>o</sup>C на полюсах, 0 <sup>o</sup>C на экваторе</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>24,6229 часа</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>1,5237 а.е., то есть 228 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>687 земных суток</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>24,1 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>3,7 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 5 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>1,9<sup>.</sup>10<sup>27</sup>кг. (в 318 раз больше массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>143760 км. (в 11,2 раза больше диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>1,31 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>-160 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>9,93 часа</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>5,203 а.е., то есть 778 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>11,86 лет</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>13,1 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>25,8 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 6 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>5,68<sup>.</sup>10<sup>26</sup>кг. (95 раз больше массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>120420 км. (9,46 раза больше диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>0,71 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>-150 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>10,54 часа</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>9,54 а.е., то есть 1427 млн.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>29,46 года</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>9,6 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>11,3 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 7 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>8,7<sup>.</sup>10<sup>25</sup>кг. (14,5 раз больше массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>51300 км. (4 раза больше диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>1,27 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>-220 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>17,23 часа</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>19,2 а.е., то есть 2,86 млрд.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>84 года</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>6,8 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>9 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 8 %>

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>1<sup>.</sup>10<sup>26</sup>кг. (17,2 раз больше массы Земли)</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>49500 км. (3,9 раза больше диаметра Земли)</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>1,77 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>-213 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Длина суток:</th><th>17,87 часа</th></tr>
		<tr align = "left" ><th>Расстояние от Cолнца(среднее):</th><th>30 а.е., то есть 4,5 млрд.км.</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>165 лет</th></tr>
		<tr align = "left" ><th>Скорость вращения по орбите:</th><th>5,4 км/c</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>11,6 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% else %>

<% if @planet.id == 9 %> 

	<table width = "100%", border = "2">
		<tr align = "left" ><th>Масса:</th><th>2<sup>.</sup>10<sup>30</sup>кг.</th></tr>
		<tr align = "left" ><th>Диаметр:</th><th>1392000 км.</th></tr>
		<tr align = "left" ><th>Плотность:</th><th>1,416 г/см<sup>3</sup></th></tr>
		<tr align = "left" ><th>Температура поверхности:</th><th>+5500 <sup>o</sup>C</th></tr>
		<tr align = "left" ><th>Период оборота по орбите(лет):</th><th>88 земных суток</th></tr>
		<tr align = "left" ><th>Светимость:</th><th>3,86<sup>.</sup>10<sup>23</sup> кВт</th></tr>
		<tr align = "left" ><th>Ускорение свободного падения:</th><th>274 м/c<sup>2</sup></th></tr>
	</table>
</div>

<% end %><% end %><% end %><% end %><% end %><% end %><% end %><% end %><% end %>

	<p class = "center_main_text_for_planet_info", id="wt"><%= @planet.info %></p>

app/views/shared/_ss.html.erb
<div id="wt", class ="center_main_text"> 
	<p>Солнечная система — планетная система, включающая в себя центральную звезду — Солнце — и все естественные космические объекты, обращающиеся вокруг Солнца. Она сформировалась путём гравитационного сжатия газопылевого облака примерно 4,57 млрд лет назад. Обратите внимание: солнце - это не планета.

<h5>Планеты солнечной системы по порядку:</h5>
<%= image_tag("ss.jpg", alt: "Rails") %>

<p><strong><u>Солнечная система</u></strong></p>

Ученые выдвигают множество версий возникновения нашей Солнечной системы. В сороковых годах прошлого столетия Отто Шмидт выдвинут гипотезу о том, что Солнечная система возникла потому что холодные пылевые облака притянулись к Солнцу. С течением времени облака сформировали основы будущих планет. В современной науке именно теория Шмидта является основной.

Солнечная система представляет собой лишь малую часть большой галактики под названием Млечный Путь. В Млечный Путь входит более ста миллиардов различных звезд. Для осознания столь простой истины человечеству понадобились тысячелетия. Открытие солнечной системы произошло не сразу, шаг за шагом, на основании побед и ошибок, формировалась система знаний. Основной базой для изучения Солнечной системы были знания о Земле.

<p><strong><u>Основы и теории</u></strong></p>

Основными вехами в изучении Солнечной системы являются современная атомарная система, гелиоцентрическая система Коперника и Птолемея. Наиболее вероятной версией происхождения системы считают теорию Большого взрыва. В соответствии с ней, формирование галактики началось с «разбегания» элементов мегасистемы. На рубеже непроглядного хауса зародилась наша Солнечная система.

Основу всего составляет Солнце – 99,8% от всего объема, на долю планет приходится 0,13%, оставшиеся 0,0003% составляют различные тела нашей системы.

Учеными принято деление планет на две условные группы. К первой относятся планеты типа Земля: собственно сама Земля, Венера, Меркурий. Основными отличительными характеристиками планет первой группы является относительно небольшая площадь, твердость, небольшое количество спутников. Ко второй группе относятся Уран, Нептун и Сатурн – их отличают большие размеры (планеты гиганты), их формируют газы гелия и водорода.

Помимо Солнца и планет к нашей системе относятся также планетарные спутники, кометы, метеориты и астероиды.

Особое внимание следует обратить на астероидные пояса, которые находятся между Юпитером и Марсом, и между орбитами Плутона и Нептуна. На данный момент в науки нет однозначной версии возникновения таких образований.

<p><strong><u>Планетой быть не суждено</u></strong></p>

Плутон со времён своего открытия и до 2006 года считался планетой, но позже во внешней части Солнечной Системы было открыто множество небесных тел, сопоставимых по размером с Плутоном и даже превышающих его. Во избежание путаницы было дано новое определение планеты. Плутон не попал под это определение, так что ему был присвоен новый "статус" - карликовая планета. Так что, Плутон может служить ответом на вопрос: раньше он считался планетой, а теперь - нет. Однако, некоторые учёные продолжают считать, что Плутон должен быть переклассифицирован обратно в планету.

<p><strong><u>Прогнозы ученых</u></strong></p>

На основании исследований ученые говорят о том, что солнце приближается к середине своего жизненного пути. Невообразимо представить себе, что будет если Солнце погаснет. Но ученые говорят, что это не только возможно, но и неизбежно.

Возраст Солнца определили при помощи новейших компьютерных разработок и выяснили, что насчитывает он около пяти миллиардов лет. По астрономическим законом жизнь звезды, подобной Солнцу, длится около десяти миллиардов лет. Таким образом, наша солнечная система находится на середине жизненного цикла.

Что же ученые подразумевают под словом «погаснет»? Огромная солнечная энергия представляет собой энергию водорода, который в ядре становится гелием. Каждую секунду около шестисот тонн водорода в ядре Солнца перерабатывается в гелий. По подсчетам ученых, Солнце уже израсходовало большую часть своих запасов водорода.

</div>